# this is a file that describes how the frontend and backend docker containers will communicate with each other
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      # Ignore the folder
      - /frontend/node_modules
      # allow frontend to communicate with backend
    environment:
        - REACT_APP_API_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      # Ignore the folder
      - /backend/__pycache__